# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('response_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('user_attempt', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_card', to='chinese_tutor.FlashCard')),
            ],
        ),
    ]
