# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattempt',
            old_name='user_attempt',
            new_name='user_response',
        ),
    ]
